services:
    jenkins:
        container_name: jenkins
        image: 'jenkins/jenkins:lts-jdk17'
        restart: on-failure
        ports:
            - '50000:50000'
            - '8080:8080'
        volumes:
            - jenkins-data:/var/jenkins_home
        networks:
            - jenkins-network

networks:
    jenkins-network:
        name: jenkins-network

volumes:
    jenkins-data:
        name: jenkins-data