services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6388:6379"
    networks:
      - dragonfly-network
    command: redis-server --requirepass Tahun2024,-
    
  # redis-commander:
  #   image: rediscommander/redis-commander
  #   container_name: redis-commander
  #   environment:
  #     - REDIS_HOSTS=redis
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - redis-network
  #   depends_on:
  #     - redis

networks:
  dragonfly-network:
    external: true
