version: '3.8'

services:
  drupal:
    image: drupal:latest
    container_name: drupal
    ports:
      - "8075:80"
    volumes:
      - drupal-data:/var/www/html
    environment:
      - DRUPAL_DB_HOST=mysql
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=root
      - DRUPAL_DB_PASSWORD=root
    networks:
      - mysql-network
      - drupal-network

networks:
  drupal-network:
    name: drupal-network
  mysql-network:
    external: true

volumes:
  drupal-data:
    name: drupal-data
    driver: local
    driver_opts:
      type: none
      device: /home/developer/compose/drupal/drupal-data
      o: bind
