services:
  web:
    image: nandanramdani/perpus:main
    container_name: perpus
    env_file:
      - .env
    ports:
      - "8070:8020"
    networks:
      - perpus-network
    volumes:
      - perpus_data:/opt/app/web_apps/media

networks:
  perpus-network:
    name: perpus-network

volumes:
  perpus_data:
    name: perpus_data
