services:
    metabase:
        image: metabase/metabase
        container_name: metabase
        ports:
            - '3001:3000'
        networks:
            - metabase-network
networks:
    metabase-network:
        name: metabase-network
