version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://grafana.straile.blue:8074
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "8074:3000"
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - monitoring
    deploy:
      mode: global

volumes:
  prometheus_data:
    name: prometheus_data
  grafana_data:
    name: grafana_data

networks:
  monitoring:
    name: monitoring
