version: '3'

services:
  web:
    image: nandanramdani/perpus:main
    container_name: perpus
    environment:
      SECRET: "vlfcy^p(+g4l*@u=6s9m_r73^#ac9qb2t$o@jagdor2ncd*soe"
      DEBUG: 0
      ALLOWED_HOST: perpus.straile.blue
      CSRF_TRUSTED_ORIGINS: https://perpus.straile.blue
      DB_HOST: mysql
      DB_PASSWORD: root
    ports:
      - "8070:8020"
    networks:
      - perpus-network
      - mysql-network
    volumes:
      - perpus_data:/opt/app/web_apps/media

networks:
  perpus-network:
    name: perpus-network
  mysql-network:
    external: true

volumes:
  perpus_data:
    name: perpus_data
