services:
  app:
    image: drupal
    container_name: drupal
    ports:
      - "8075:80"
    volumes:
      - drupal-data:/var/www/html
    networks:
      - drupal-network

volumes:
  drupal-data:
    name: drupal-data

networks:
  drupal-network:
    name: drupal-network