services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    env_file:
      - .env
    ports:
      - "8072:80"
    volumes:
      - ./nextcloud-data:/var/www/html
    networks:
      - nextcloud-network

networks:
  nextcloud-network:
    name: nextcloud-network