version: "3"

services:
  edaily:
    image: edaily:dev
    container_name: edaily
    ports:
      - "8071:8020"
    environment:
      SENTINELS: redis-sentinel:26379
      POSTGR_DB_HOST: postgres
      DEV: 1
      WEB_ONLY: 1
      CELERY_RESULT_BACKEND: sentinel://redis-sentinel:26379/1
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    networks:
      - edaily-network
      - pgsql-network
      - redis-sentinel-network
      - rabbitmq-network

networks:
  edaily-network:
    name: edaily-network
    
  pgsql-network:
    external: true
  redis-sentinel-network:
    external: true
  rabbitmq-network:
    external: true
