services:
  web:
    image: ghcr.io/naandan/waapi:main
    container_name: waapi
    restart: always
    env_file:
      - .env
    ports:
      - "8073:3000"
    networks:
      - waapi-network
      # - mysql-network

networks:
  waapi-network:
    name: waapi-network
  # mysql-network:
  #   external: true
