services:
  grav:
    image: grav:latest
    container_name: grav
    ports:
      - 8085:80
    volumes:
      # - ./grav-data:/var/www/html
      - grav-data:/var/www/html

volumes:
  grav-data:
    driver: local
    driver_opts:
      type: none
      device: /home/nandan/mount/grav
      o: bind