services:
  master:
    image: redis
    container_name: redis-master
    restart: always
    ports:
      - "6380:6380"
    networks:
      - redis-sentinel-network
    command: redis-server --port 6380

  sentinel:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel
    restart: always
    env_file:
      - .env
    ports:
      - "26379:26379"
    networks:
      - redis-sentinel-network
    depends_on:
      - master

networks:
  redis-sentinel-network:
    name: redis-sentinel-network
