services:
  master:
    image: redis
    container_name: redis-master
    networks:
      - redis-sentinel-network

  sentinel:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel
    env_file:
      - .env.sentinels
    ports:
      - "26379:26379"
    networks:
      - redis-sentinel-network
    depends_on:
      - master

networks:
  redis-sentinel-network:
    name: redis-sentinel-network
