services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    name: rabbitmq-network

volumes:
  rabbitmq-data:
    name: rabbitmq-data