services:
  backend:
    image: ghcr.io/naandan/whatsapp-go-backend:main
    container_name: wago
    restart: always
    ports:
      - "8060:8000"
    env_file:
      - .env.backend
    networks:
      - whatsapp-go-network

  frontend:
    image: ghcr.io/naandan/whatsapp-go-frontend:main
    container_name: ware
    restart: always
    ports:
      - "8061:80"
    networks:
      - whatsapp-go-network
    volumes:
      - ./config.json:/usr/share/nginx/html/config.json
    depends_on:
      - backend

networks:
  whatsapp-go-network:
    name: whatsapp-go-network