version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: 'Admin#1234'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: sqlserver
    ports:
      - '8082:8080'
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
    name: sqlserver_data
