version: '3.8'

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8070:80
    environment:
      WORDPRESS_DB_HOST: 192.168.109.80
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
#      - wordpress-data:/var/www/html
       - ./wordpress-data:/var/www/html
    networks:
      - wordpress-network

#volumes:
#  wordpress-data:
#    name: wordpress-data

networks:
  wordpress-network:
    name: wordpress-network
