version: '3'

services:
  web:
    image: nandanramdani/waapi:main
    container_name: waapi
    environment:
      SECRET: secret
      PORT: 3000
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: waapi
      DB_PORT: 3306
    ports:
      - "8073:3000"
    networks:
      - waapi-network
      - mysql-network

networks:
  waapi-network:
    name: waapi-network
  mysql-network:
    external: true
