services:
  n8nio:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - '5678:5678'
    env_file:
      - .env
    volumes:
      - 'n8n-data:/home/node/.n8n'
    networks:
      - n8n-network

volumes:
  n8n-data:
    name: n8n-data

networks:
  n8n-network:
    name: n8n-network
