version: '3.1'

services:
  grav:
    image: grav:latest
    container_name: webhoster
    ports:
      - 8085:80
    volumes:
      - grav-data:/var/www/html

volumes:
  grav-data:
    driver: local
    driver_opts:
      type: none
      device: /home/nandan/data/grav
      o: bind
      
# version: '3.1'

# services:
#   grav:
#     image: grav:latest
#     container_name: webhoster
#     ports:
#       - 8085:80
#     volumes:
#       - /home/nandan/data/grav:/var/www/html
