version: '3.1'

services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost
    ports:
      - 8001:2368
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: root
      database__connection__database: ghost
      url: http://localhost:8001
      NODE_ENV: development
    networks:
      - ghost-network
      - mysql-network
    volumes:
      - ghost-data:/var/lib/ghost/content
      - ./config.production.json:/var/lib/ghost/config.production.json

volumes:
  ghost-data:
    name: ghost-data
networks:
  ghost-network:
    name: ghost-network
  mysql-network:
    external: true
