version: '3.8'

services:
  wordpress:
    image: wordpress
    container_name: flipbyte
    restart: always
    ports:
      - 8071:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: flipbyte
    volumes:
      - flipbyte-data:/var/www/html
    networks:
      - flipbyte-network
      - mysql-network


volumes:
  flipbyte-data:
    name: flipbyte-data

networks:
  flipbyte-network:
    name: flipbyte-network
  mysql-network:
    external: true
