version: "3"

services:
  pgsql:
    image: postgres:latest
    container_name: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    networks:
      - pgsql-network
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    networks:
      - pgsql-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  pgsql-network:
    name: pgsql-network
volumes:
  pgsql-data:
    name: pgsql-data
  pgadmin-data:
    name: pgadmin-data

