services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: 'Master!23'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sqlserver-network

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   environment:
  #     ADMINER_DEFAULT_SERVER: sqlserver
  #   ports:
  #     - '8082:8080'
  #   depends_on:
  #     - sqlserver
  #   networks:
  #     - sqlserver-network

networks:
  sqlserver-network:
    name: sqlserver-network

volumes:
  sqlserver_data:
    name: sqlserver_data
